name: Build and deploy docker image on EC2 instances

on:
  push:
    paths:
      - 'web-app/app.py'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and push docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest -f ./web-app/Dockerfile ./web-app
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Deploy docker image to EC2 instance 1 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
              sudo yum install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
            fi
            
            aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
            
            sudo docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            sudo docker stop myapp || true
            sudo docker rm myapp || true 
            sudo docker run -d --name myapp -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy docker image to EC2 instance 2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
              sudo yum install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
            fi
            
            aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
            
            sudo docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            sudo docker stop myapp || true
            sudo docker rm myapp || true 
            sudo docker run -d --name myapp -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest