name: Build and deploy docker image on EC2 instances

on:
  push:
    paths:
      - 'web-app/app.py'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy docker image to EC2 instance 1 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            docker stop myapp || true
            docker rm myapp || true 
            docker run -d --name myapp -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy docker image to EC2 instance 2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            docker stop myapp || true
            docker rm myapp || true 
            docker run -d --name myapp -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest